# Generated by Django 2.2.6 on 2019-11-01 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stops', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_processed', models.BooleanField()),
                ('unprocessed_reason', models.SmallIntegerField(blank=True, choices=[(0, 'At more than one stop'), (1, 'Too far from route'), (2, 'Beyond final stop')], null=True)),
                ('is_at_stop', models.BooleanField(blank=True, null=True)),
                ('to_next_stop_ratio', models.FloatField(blank=True, null=True)),
                ('current_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stops.Stop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Route')),
            ],
            options={
                'ordering': ['route', 'vehicle_id', 'date'],
            },
        ),
        migrations.AddIndex(
            model_name='vehiclelocation',
            index=models.Index(fields=['is_processed'], name='vehicle_loc_is_proc_e72713_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclelocation',
            unique_together={('route', 'vehicle_id', 'date')},
        ),
    ]
