# Generated by Django 2.2.6 on 2019-12-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelocation',
            name='unprocessed_reason',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Too far from route'), (2, 'Beyond final stop')], null=True),
        ),
    ]
