# Generated by Django 2.2.6 on 2019-12-18 15:26

from django.conf import settings
from django.db import migrations
from django.db.models import Q


def delete_invalid_coordinates(apps, schema_editor):
    VehicleLocation = apps.get_model('vehicle_locations', 'VehicleLocation')

    num_deleted, _ = VehicleLocation.objects \
            .filter(~Q(latitude__range=(settings.MIN_LAT, settings.MAX_LAT)) | ~Q(longitude__range=(settings.MIN_LONG, settings.MAX_LONG))) \
            .order_by() \
            .delete()
    print('\nNum deleted rows: {}'.format(num_deleted))


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_locations', '0002_auto_20191204_2038'),
    ]

    operations = [
        migrations.RunPython(delete_invalid_coordinates, migrations.RunPython.noop),
    ]

