# Generated by Django 2.2.6 on 2020-04-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_locations', '0004_delete_unneeded_fk_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehiclelocation',
            name='vehicle_loc_is_proc_e72713_idx',
        ),
        migrations.AddIndex(
            model_name='vehiclelocation',
            index=models.Index(fields=['route', 'date'], name='vehicle_loc_route_i_ff2826_idx'),
        ),
    ]
