# Generated by Django 2.2.6 on 2019-11-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
