# Generated by Django 2.2.6 on 2019-11-10 14:09

from django.db import migrations


def fill_display_name(apps, schema_editor):
    Stop = apps.get_model('stops', 'Stop')

    for stop in Stop.objects.all():
        stop.display_name = stop.name
        stop.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0002_stop_display_name'),
    ]

    operations = [
        migrations.RunPython(fill_display_name, lambda *args: None),
    ]
