# Generated by Django 2.2.6 on 2019-11-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0003_fill_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='display_name',
            field=models.CharField(max_length=50),
        ),
    ]
