
UNPROC_REASON_MULTIPLE_STOPS = 0
UNPROC_REASON_TOO_FAR = 1
UNPROC_REASON_BEYOND_FINAL_STOP = 2

UNPROC_REASON_CHOICES = [
    (UNPROC_REASON_MULTIPLE_STOPS, 'At more than one stop'),
    (UNPROC_REASON_TOO_FAR, 'Too far from route'),
    (UNPROC_REASON_BEYOND_FINAL_STOP, 'Beyond final stop'),
]

